name: 索引爬虫 docsearch

on:
  push:
    branches:
      - main

jobs:
  algolia:
    name: 开始任务
    runs-on: ubuntu-latest
    steps:

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run scraper
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        run: |
          CONFIG="$(cat docsearch.json)"
          docker run -i --rm \
            -e APPLICATION_ID=${ALGOLIA_APP_ID} \
            -e API_KEY=${ALGOLIA_API_KEY} \
            -e CONFIG="${CONFIG}" \
            algolia/docsearch-scraper